name: aniview
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0-290.4.beta

dependencies:
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.1
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  flutter:
    sdk: flutter
  get_it: ^9.0.5
  google_fonts: ^6.3.2
  http: ^1.6.0
  intl: ^0.20.2
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
